apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deis-router
  namespace: kube-system
  labels:
    k8s-app: deis-router
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: deis-router
  template:
    metadata:
      labels:
        app: deis-router
    spec:
      containers:
      - name: deis-router
        image: ## Image is dynamically set by `make set-image` as part of dev deployment ##
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          hostPort: 10080
        - containerPort: 6443
          hostPort: 10443
        - containerPort: 2222
          hostPort: 10022
        - containerPort: 9090
          hostPort: 19090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1
