apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: index.tenxcloud.com/docker_library/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    router.deis.io/routable: "true"
    app: nginx
  annotations:
    router.deis.io/domains: nginx.xiucall.com
    router.deis.io/appCertificates: nginx.xiucall.com:nginx-app-tls
    router.deis.io/clientCertificates: nginx.xiucall.com:nginx-client-tls
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
